
path: /Users/eloi/Documents/Eloi/UQAC/T2/Vision_Artificielle_et_Traitement_des_Images/TP/Projet/train-yolov8-custom-dataset-step-by-step-guide/local_env/data/  # dataset root dir
train: images/train  # train images (relative to 'path')
val: images/train  # val images (relative to 'path')

# Classes
names:
  0: basilic
